### ISSUE TITLE
joomla and drupal have the same url in technology-repositories.json 

### ISSUE THREAD

**Issue by 0xAwali** [trickest/wordlists#3]
![Screenshot_2022-09-08_16_30_24](https://user-images.githubusercontent.com/54332136/189149527-86849909-c47e-4fa8-be69-d4e2a9bc82b8.jpg)

**Comment by mhmdiaa** [comment]
Thanks @0xAwali! I just corrected the repository URL and the next scheduled run of the workflow will correct the wordlist.
